
repos:
  # Several generic fixes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-yaml
        args: [--unsafe]

  # Sort python imports
  # Use fork until https://github.com/psf/black/issues/4175 is fixed (possibly never)
  - repo: https://github.com/wimglenn/reorder-python-imports-black
    rev: v3.12.0
    hooks:
    - id: reorder-python-imports

  # Format the code with a conventional PEP8 style
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
