
# Ignore any sample data: this should be processed as-is
exclude: '^.*.dat$'

repos:
  # Several generic fixes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-yaml

  # Sort python imports
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.5
    hooks:
    - id: reorder-python-imports
      language_version: python3.8

  # Format the code with a conventional PEP8 style
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.8
