"""empty message

Revision ID: c715763ad094
Revises: a0b4caa55845
Create Date: 2020-06-06 12:54:17.678562

"""
from alembic import op
import sqlalchemy as sa
import backend
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'c715763ad094'
down_revision = 'a0b4caa55845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
