"""empty message

Revision ID: eec0897350c7
Revises:
Create Date: 2020-06-07 19:23:42.709248

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import backend


# revision identifiers, used by Alembic.
revision = "eec0897350c7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum("GUI", "CHAT", "UPDATE_PLAYER", name="eventtype"),
            nullable=False,
        ),
        sa.Column("details", backend.model.JSONEncodedDict(), nullable=True),
        sa.Column("public_visibility", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_game_events_game_id"), "game_events", ["game_id"], unique=False
    )
    op.create_table(
        "game_event_visibilities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["game_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("game_event_visibilities")
    op.drop_index(op.f("ix_game_events_game_id"), table_name="game_events")
    op.drop_table("game_events")
    # ### end Alembic commands ###
