"""empty message

Revision ID: e4444c9c8365
Revises: 89cc0d5ffc67
Create Date: 2020-05-27 23:41:37.687533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4444c9c8365'
down_revision = '89cc0d5ffc67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('users', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('user', 'users')
    # ### end Alembic commands ###
