# This workflow will install Python dependencies, run tests and lint.
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test backend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    # Cache venv
    - uses: actions/cache@v2
      with:
        path: venv
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    - name: Install dependencies into venv
      run: |
        [ -d "venv" ] || python -m pip install --upgrade pip wheel virtualenv
        [ -d "venv" ] || virtualenv venv
        source venv/bin/activate
        pip install -r requirements.txt
        pip install .[dev]
    # Cache pre-commit
    - uses: actions/cache@v2
      with:
        path: cache-pre-commit
        key: ${{ runner.os }}-precommit
    - name: Lint with pre-commit
      run: |
        pre-commit run --all
      env:
        PRE_COMMIT_HOME: cache-pre-commit
    - name: Test with pytest
      run: |
        cp .env.example .env
        pytest
