# This workflow will install Python dependencies, run tests and lint.
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test backend

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.8.3"]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - name: Install dependencies
      run: |
        poetry install
    - name: Test with pytest
      run: |
        cp .env.example .env
        pytest
